bcvsolutions/CzechIdMng

- Realization/frontend/czechidm-core/src/components/advanced/Content/AbstractTableContent.js
Issue: 
https://redmine.czechidm.com/issues/852
> #852 pagination

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/rest/impl/SysProvisioningOperationController.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/scheduler/task/impl/CleanProvisioningQueueTaskExecutor.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/scheduler/task/CleanProvisioningQueueTaskExecutorIntegrationTest.java
- Realization/frontend/czechidm-acc/src/content/provisioning/ProvisioningOperationTable.js
- Realization/frontend/czechidm-acc/src/locales/cs.json
- Realization/frontend/czechidm-acc/src/locales/en.json
- Realization/frontend/czechidm-acc/src/redux/ProvisioningOperationManager.js
- Realization/frontend/czechidm-acc/src/services/ProvisioningOperationService.js
- Realization/frontend/czechidm-core/src/locales/cs.json
- Realization/frontend/czechidm-core/src/locales/en.json
commits: https://github.com/bcvsolutions/CzechIdMng/commit/b8e4a2508c6753a4b6cd96142f1a9f8361e6f9bb
https://github.com/bcvsolutions/CzechIdMng/commit/c33163fd4813b2ce01fe767494d2b8b3019548b2
> #871 controller, lrt, test, frontend

- Realization/frontend/czechidm-core/src/locales/cs.json
- Realization/frontend/czechidm-core/src/locales/en.json
Change of help message for password policy
> edit default policy text 1091

- Realization/backend/vs/src/main/java/eu/bcvsolutions/idm/vs/service/impl/DefaultVsRequestService.java
- Realization/backend/vs/src/main/resources/eu/bcvsolutions/idm/templates/VsRequestCreated.xml
commit: https://github.com/bcvsolutions/CzechIdMng/commit/8cc8306859d351c9bffd94f4e4965f0626154384
> #1001 notification vs fix

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmPasswordPolicyService.java
commit : https://github.com/bcvsolutions/CzechIdMng/commit/d4e92a8d162e428dde91434706d7246d67ad6cae
> 1123 - fix

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/dto/SysSyncIdentityConfigDto.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/entity/SysSyncIdentityConfig.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/AbstractSynchronizationExecutor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/ContractSliceSynchronizationExecutor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/ContractSynchronizationExecutor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/IdentitySynchronizationExecutor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/RoleSynchronizationExecutor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/TreeSynchronizationExecutor.java
- Realization/backend/acc/src/main/resources/eu/bcvsolutions/idm/acc/sql/postgresql/V8_02_003__create-contract-during-synchronization.sql
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/sync/IdentitySyncTest.java
- Realization/frontend/czechidm-acc/src/content/sync/SyncIdentityConfig.js
- Realization/frontend/czechidm-acc/src/locales/cs.json
- Realization/frontend/czechidm-acc/src/locales/en.json
Please after you resolve feedback merge it into develop :1st_place_medal:  thank you
> #1047 create default contract during synchronization

- Realization/frontend/czechidm-core/src/components/advanced/Form/TextFormAttributeRenderer.js
- Realization/frontend/czechidm-core/src/components/basic/AbstractFormComponent/AbstractFormComponent.js
- Realization/frontend/czechidm-core/src/components/basic/TextArea/README.md
- Realization/frontend/czechidm-core/src/components/basic/TextArea/TextArea.js
- Realization/frontend/czechidm-core/src/components/basic/TextField/README.md
- Realization/frontend/czechidm-core/src/components/basic/TextField/TextField.js
slight changes of names and behavior fix
> #1711 Trim or warn about leading and trailing whitespaces

- Realization/frontend/czechidm-acc/src/locales/cs.json
- Realization/frontend/czechidm-acc/src/locales/en.json
- Realization/frontend/czechidm-core/src/components/basic/SelectBox/OptionDecorator.js
- Realization/frontend/czechidm-core/src/components/basic/SelectBox/ValueDecorator.js
- Realization/frontend/czechidm-core/src/locales/cs.json
- Realization/frontend/czechidm-core/src/locales/en.json
> #1294 Eav - add localization for core long running tasks

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/domain/converter/MultipleSecureTextFormPropertyConverter.java
https://redmine.czechidm.com/issues/2212
> #2212 Added property converter for array of GuardedStrings

- Realization/backend/core/core-impl/src/main/resources/eu/bcvsolutions/idm/workflow/role/changeIdentityRoles.bpmn20.xml
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/workflow/notification/SendNotificationToApplicantAndImplementerTest.java
https://redmine.czechidm.com/issues/3012
> 3012 fixed notification about role request

- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/service/IdmRoleRequestService.java
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/scheduler/api/service/AbstractLongRunningTaskExecutor.java
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/scheduler/api/service/LongRunningTaskExecutor.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultEntityEventManager.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmRoleRequestService.java
https://redmine.czechidm.com/issues/3048
> Refactor locking

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccAccountManagementService.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/service/impl/AccountProtectionSystemTest.java
https://redmine.czechidm.com/issues/3070
> [#3070] Fix re-enabling account after protection for cross domain roles

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/config/domain/WebMvcRegistrationsConfig.java
https://redmine.czechidm.com/issues/3098
PR from the current version:
https://github.com/bcvsolutions/CzechIdMng/pull/190
> 3098, mitigating CVE-2022-22965 Spring vulnerability

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/event/processor/role/RoleCompositionDeleteProcessor.java
https://redmine.czechidm.com/issues/3090
> 3090, fixed an issue with repeated role composition removal

- Realization/frontend/czechidm-core/src/components/basic/AbstractForm/AbstractForm.js
https://redmine.czechidm.com/issues/3034
> #3034 fixed validation for not rendered attrs in projection

- Realization/frontend/czechidm-core/src/components/advanced/Form/EavForm.less
- Realization/frontend/czechidm-core/src/components/basic/TextArea/TextArea.less
- Realization/frontend/czechidm-core/src/components/components.less
https://redmine.czechidm.com/issues/3102
> #3054 resizable text area

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/event/processor/role/RoleCompositionDeleteProcessor.java
https://redmine.czechidm.com/issues/2957
> #2957 remove role composition always as sync to prevent warning state

- Realization/frontend/czechidm-core/src/components/advanced/Navigation/NavigationSearch.js
- Realization/frontend/czechidm-core/src/locales/cs.json
- Realization/frontend/czechidm-core/src/locales/en.json
https://redmine.czechidm.com/issues/3106
> 3106, made the global search field more contrasting

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccAccountManagementService.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/service/impl/AccountProtectionSystemTest.java
https://redmine.czechidm.com/issues/3070
> [#3093] Fix re-enabling account after protection for cross domain roles

- Realization/frontend/czechidm-core/src/content/identity/IdentityRoleTable.js
https://redmine.czechidm.com/issues/3128
> [#3128] Fix IdentityRoleTable when using identity column

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmRoleRequestService.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmRoleRequestServiceIntegrationTest.java
https://redmine.czechidm.com/issues/3132
> 3132 duplicate sub roles for parent auto role

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/rest/impl/AccAccountController.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/audit/service/impl/DefaultIdmLoggingEventExceptionService.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/audit/service/impl/DefaultIdmLoggingEventPropertyService.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/audit/service/impl/DefaultIdmLoggingEventService.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmAutomaticRoleRequestService.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/rest/impl/IdmLongRunningTaskItemController.java
- Realization/backend/core/core-impl/src/test/resources/application-test-postgresql.properties
[…](https://redmine.czechidm.com/issues/3131)
> [#3131] Require transaction when fetching embedded entities in REST controllers

- Realization/frontend/czechidm-acc/src/content/system/SystemAttributeMappingDetail.js
https://redmine.czechidm.com/issues/3116
> 3116, fixed the issue with the where attribute is used not being shown

- .github/workflows/maven-manual.yml
Improved manual github action.
Now all tests are executed.
Even if some module weill fail it will continue with other modules.
Correctly fail in the end if there is some error.
> Kucerar/fix GitHub actions test

- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/security/api/domain/IdmGroupPermission.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/security/rest/impl/LoginController.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/security/rest/impl/LoginControllerRestTest.java
- Realization/frontend/czechidm-core/src/locales/cs.json
- Realization/frontend/czechidm-core/src/locales/en.json
https://redmine.czechidm.com/issues/3140
> #3140 added new permission for login without cas

- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/scheduler/api/service/AbstractLongRunningTaskExecutor.java
https://redmine.czechidm.com/issues/3115
> #3115 removed ignoring of tasks in waiting state

- .github/workflows/maven-manual.yml
- .github/workflows/maven.yml
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/domain/AccResultCode.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/event/SystemAttributeMappingEvent.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/event/processor/SystemAttributeMappingDeleteProcessor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/event/processor/SystemAttributeMappingSaveProcessor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/event/processor/SystemAttributeMappingUpdateProcessor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/scheduler/task/impl/SystemAttributeMappingStrategyRecalculationTaskExecutor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/api/SysSystemAttributeMappingService.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/AbstractProvisioningExecutor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultSysSystemAttributeMappingService.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/scheduler/task/impl/SystemAttributeMappingStrategyRecalculationTaskExecutorTest.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/service/impl/DefaultSysProvisioningServiceTest.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/service/impl/ProvisioningMergeTest.java
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/domain/CoreResultCode.java
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/utils/ParameterConverter.java
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/scheduler/api/service/AbstractLongRunningTaskExecutor.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/scheduler/service/impl/DefaultLongRunningTaskManagerIntegrationTest.java
- Realization/backend/rpt/rpt-impl/src/main/java/eu/bcvsolutions/idm/rpt/report/provisioning/ChangesOnSystemReportExecutor.java
- Realization/backend/rpt/rpt-impl/src/test/java/eu/bcvsolutions/idm/rpt/report/provisioning/ChangesOnSystemReportIntegrationTest.java
- Realization/frontend/czechidm-acc/src/content/role/RoleSystemAttributeDetail.js
- Realization/frontend/czechidm-acc/src/locales/cs.json
- Realization/frontend/czechidm-acc/src/locales/en.json
- Realization/frontend/czechidm-core/src/locales/cs.json
- Realization/frontend/czechidm-core/src/locales/en.json
https://redmine.czechidm.com/issues/1362
> 1362 conflict mapping strategy

- Realization/frontend/czechidm-core/src/content/generatevalues/GenerateValueTable.js
https://redmine.czechidm.com/issues/3099
> 3099, fixed generator name localization for custom generators

- Realization/backend/rpt/rpt-impl/src/main/java/eu/bcvsolutions/idm/rpt/report/general/GeneralEntityExport.java
- Realization/backend/rpt/rpt-impl/src/test/java/eu/bcvsolutions/idm/rpt/report/general/GeneralFormableEntityExportIntegrationTest.java
https://redmine.czechidm.com/issues/3181
> 3181, fixed the export (report) of form values

- Realization/backend/acc/src/main/resources/eu/bcvsolutions/idm/acc/sql/postgresql/V12_03_002__account_form_attributes.sql
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/config/flyway/DefaultIdmFlywayComparator.java
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/config/flyway/IdmFlywayComparator.java
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/config/flyway/IdmFlywayPostProcessor.java
https://redmine.czechidm.com/issues/3189
> [#3189] Fix executing Flyway migrations

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/repository/filter/EavCodeContractByManagerFilter.java
https://redmine.czechidm.com/issues/3129
> 3129, fixed EAV subordinates filter

- Realization/backend/rpt/rpt-impl/src/main/java/eu/bcvsolutions/idm/rpt/service/DefaultReportManager.java
https://redmine.czechidm.com/issues/3218
> 3218, fixed a bug which caused reports to generate only one line

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/api/AccSchemaFormAttributeService.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccAccountManagementService.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccSchemaFormAttributeService.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultSysSchemaAttributeService.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/bulk/action/impl/IdentityAccountManagementBulkActionTest.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/provisioning/ProvisioningOtherAccountsTest.java
https://redmine.czechidm.com/issues/3197#note-18
> 3197, fixed an issue with identity account recalculation

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultSysSyncConfigService.java
https://redmine.czechidm.com/issues/3197#note-24
> [#3197] Fix cyclic dependency

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccAccountManagementService.java
https://redmine.czechidm.com/issues/3197#note-21
> [#3197] Removed fetching embedded contract from AbstractRoleAssignment

- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmConfidentialStorageIntegrationTest.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/rest/impl/IdmRoleRequestControllerRestTest.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/workflow/permissions/ChangeIdentityPermissionTest.java
> 3197, fixed tests in core impl

- Realization/frontend/czechidm-acc/src/content/account/AccountDetail.js
the error is now shown in the account detail
https://redmine.czechidm.com/issues/3197#note-36
> 3197, when an error occurs during account loading from a system,

- Realization/frontend/czechidm-acc/src/locales/cs.json
https://redmine.czechidm.com/issues/3197#note-35
> 3197, fixed a typo in localization

- Realization/frontend/czechidm-acc/src/content/account/AccountDetail.js
https://redmine.czechidm.com/issues/3197#note-34
> [#3197] Fix grid spacing

- Realization/frontend/czechidm-core/src/content/requestrole/RoleRequestDetail.js
https://redmine.czechidm.com/issues/3197#note-48
> [#3197] Fix error when sending empty role request

- Realization/frontend/czechidm-acc/component-descriptor.js
https://redmine.czechidm.com/issues/3197#note-56
> 3197, added account info component to be shown in audit

- Realization/backend/acc/src/main/resources/eu/bcvsolutions/idm/acc/sql/postgresql/V13_00_010__acc_account_role_valid_request.sql
https://redmine.czechidm.com/issues/3197#note-57
> [#3197] Adding missing flyway script

- Realization/frontend/czechidm-core/src/components/advanced/TabPanel/TabPanel.js
https://redmine.czechidm.com/issues/3197#note-45
https://redmine.czechidm.com/issues/3197#note-46
> [#3197] Fix displaying navigation tabs with nested routes

- Realization/frontend/czechidm-acc/module-descriptor.js
- Realization/frontend/czechidm-acc/src/content/system/SystemOwners.js
https://redmine.czechidm.com/issues/3197
> Position of tab in menu was changed and added a pink line

- MIGRATION.md
https://redmine.czechidm.com/issues/3242
> 3238, added information about IdM 13 to the upgrade guide

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/AbstractSynchronizationExecutor.java
https://redmine.czechidm.com/issues/3235
> #3235 update behavior for newly created entities and synchronization

- CHANGELOG.md
Changelog for version 13
https://redmine.czechidm.com/issues/3239
> [#3239] Update changelog

- Realization/backend/acc/pom.xml
- Realization/backend/aggregator/pom.xml
- Realization/backend/app/pom.xml
- Realization/backend/core/core-api/pom.xml
- Realization/backend/core/core-impl/pom.xml
- Realization/backend/core/core-test-api/pom.xml
- Realization/backend/core/pom.xml
- Realization/backend/example/pom.xml
- Realization/backend/ic/pom.xml
- Realization/backend/parent/pom.xml
- Realization/backend/rpt/pom.xml
- Realization/backend/rpt/rpt-api/pom.xml
- Realization/backend/rpt/rpt-impl/pom.xml
- Realization/backend/tool/pom.xml
- Realization/backend/vs/pom.xml
- Realization/frontend/czechidm-acc/package.json
- Realization/frontend/czechidm-app/package.json
- Realization/frontend/czechidm-core/package.json
- Realization/frontend/czechidm-example/package.json
- Realization/frontend/czechidm-rpt/package.json
- Realization/frontend/czechidm-tool/package.json
- Realization/frontend/czechidm-vs/package.json
https://redmine.czechidm.com/issues/3239
> 3239, upped the versions in poms and package.json

- README.md
- Realization/backend/acc/pom.xml
- Realization/backend/aggregator/pom.xml
- Realization/backend/app/pom.xml
- Realization/backend/core/core-api/pom.xml
- Realization/backend/core/core-impl/pom.xml
- Realization/backend/core/core-test-api/pom.xml
- Realization/backend/core/pom.xml
- Realization/backend/example/pom.xml
- Realization/backend/ic/pom.xml
- Realization/backend/parent/pom.xml
- Realization/backend/rpt/pom.xml
- Realization/backend/rpt/rpt-api/pom.xml
- Realization/backend/rpt/rpt-impl/pom.xml
- Realization/backend/tool/pom.xml
- Realization/backend/vs/pom.xml
- Realization/frontend/czechidm-acc/package.json
- Realization/frontend/czechidm-app/package.json
- Realization/frontend/czechidm-core/package.json
- Realization/frontend/czechidm-example/package.json
- Realization/frontend/czechidm-rpt/package.json
- Realization/frontend/czechidm-vs/package.json
https://redmine.czechidm.com/issues/3239
> 3239, 13.1 snapshot

- Realization/backend/core/core-impl/src/main/resources/eu/bcvsolutions/idm/workflow/role/changeIdentityRoles.bpmn20.xml
replace DateTimeFormatter.forPattern by DateTimeFormatter.ofPattern
> replace DateTimeFormatter.forPattern by DateTimeFormatter.ofPattern

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultSysProvisioningArchiveService.java
when used in combination with the send always strategy
https://redmine.czechidm.com/issues/3133
> 3133, fixed an issue with a compare system values report

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/task/impl/ProcessAutomaticRoleByTreeTaskExecutor.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/scheduler/task/impl/ProcessAutomaticRoleByTreeTaskExecutorIntegrationTest.java
https://redmine.czechidm.com/issues/3219
> Fix for Defect #3219, added test for the bugfix

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/eav/service/impl/AbstractFormValueService.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/eav/service/impl/DefaultFormServiceIntegrationTest.java
https://redmine.czechidm.com/issues/3254
> 3254, fixed an issue in form service for code list eavs

- Realization/backend/acc/pom.xml
- Realization/backend/aggregator/pom.xml
- Realization/backend/app/pom.xml
- Realization/backend/core/core-api/pom.xml
- Realization/backend/core/core-impl/pom.xml
- Realization/backend/core/core-test-api/pom.xml
- Realization/backend/core/pom.xml
- Realization/backend/example/pom.xml
- Realization/backend/ic/pom.xml
- Realization/backend/parent/pom.xml
- Realization/backend/rpt/pom.xml
- Realization/backend/rpt/rpt-api/pom.xml
- Realization/backend/rpt/rpt-impl/pom.xml
- Realization/backend/tool/pom.xml
- Realization/backend/vs/pom.xml
- Realization/frontend/czechidm-acc/package.json
- Realization/frontend/czechidm-app/package.json
- Realization/frontend/czechidm-core/package.json
- Realization/frontend/czechidm-example/package.json
- Realization/frontend/czechidm-rpt/package.json
- Realization/frontend/czechidm-vs/package.json
https://redmine.czechidm.com/issues/3295
> [#3295] Set version to 13.0.1

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/bulk/action/impl/IdmRoleCompositionDeleteBulkAction.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmRoleCompositionService.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/rest/impl/IdmRoleCompositionController.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/scheduler/task/impl/RemoveRoleCompositionTaskExecutorIntegrationTest.java
- Realization/frontend/czechidm-core/src/content/role/RoleCompositionTable.js
- Realization/frontend/czechidm-core/src/locales/cs.json
- Realization/frontend/czechidm-core/src/locales/en.json
- Realization/frontend/czechidm-core/src/services/RoleCompositionService.js
https://redmine.czechidm.com/issues/3248
> 3248, fixed an issue with role composisition removal

- Realization/backend/acc/pom.xml
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccAccountService.java
- Realization/backend/aggregator/pom.xml
- Realization/backend/app/pom.xml
- Realization/backend/core/core-api/pom.xml
- Realization/backend/core/core-impl/pom.xml
- Realization/backend/core/core-test-api/pom.xml
- Realization/backend/core/pom.xml
- Realization/backend/example/pom.xml
- Realization/backend/ic/pom.xml
- Realization/backend/parent/pom.xml
- Realization/backend/rpt/pom.xml
- Realization/backend/rpt/rpt-api/pom.xml
- Realization/backend/rpt/rpt-impl/pom.xml
- Realization/backend/tool/pom.xml
- Realization/backend/vs/pom.xml
- Realization/frontend/czechidm-acc/package.json
- Realization/frontend/czechidm-app/package.json
- Realization/frontend/czechidm-core/package.json
- Realization/frontend/czechidm-example/package.json
- Realization/frontend/czechidm-vs/package.json
https://redmine.czechidm.com/issues/3295#note-6
> 3295, added a lazy bean creation in accountService

- Realization/frontend/czechidm-core/src/content/requestrole/RoleConceptDetail.js
Lot of code formatting, real fix on L46 and L258
> Defect #3314 Cannot show approval task for role authorizer

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/config/domain/EntityToUuidConverter.java
https://redmine.czechidm.com/issues/3311
> 3311, fixed an issue with missing tree node parent

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultSysSystemMappingService.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultSysSystemService.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/bulk/action/impl/SystemDuplicateBulkActionTest.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/bulk/action/impl/SystemMappingDuplicateBulkActionTest.java
- Realization/frontend/czechidm-acc/src/locales/cs.json
- Realization/frontend/czechidm-acc/src/locales/en.json
https://redmine.czechidm.com/issues/3320
> 3320, fixed system duplication with connected mappings

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/bulk/action/impl/AccountDeleteBulkAction.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/dto/AccAccountDto.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/event/processor/AccountDeleteProcessor.java
- Realization/frontend/czechidm-acc/src/locales/cs.json
- Realization/frontend/czechidm-acc/src/locales/en.json
in protection
https://redmine.czechidm.com/issues/3316
> 3316, improved the implementation of removing accounts

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/security/evaluator/AccountRoleAssignmentByAccountEvaluator.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/security/evaluator/AccountRoleAssignmentByAccountEvaluatorTest.java
- Realization/frontend/czechidm-acc/src/locales/cs.json
- Realization/frontend/czechidm-acc/src/locales/en.json
https://redmine.czechidm.com/issues/3297
> 3297, added an evaluator for account role assignments

- Docker/compose/docker-compose-czechidm-H2.yml
- Docker/compose/docker-compose-czechidm.yml
- Docker/images/czechidm/Dockerfile
- Realization/backend/acc/pom.xml
- Realization/backend/aggregator/pom.xml
- Realization/backend/app/pom.xml
- Realization/backend/core/core-api/pom.xml
- Realization/backend/core/core-impl/pom.xml
- Realization/backend/core/core-test-api/pom.xml
- Realization/backend/core/pom.xml
- Realization/backend/example/pom.xml
- Realization/backend/ic/pom.xml
- Realization/backend/parent/pom.xml
- Realization/backend/rpt/pom.xml
- Realization/backend/rpt/rpt-api/pom.xml
- Realization/backend/rpt/rpt-impl/pom.xml
- Realization/backend/tool/pom.xml
- Realization/backend/vs/pom.xml
- Realization/frontend/czechidm-acc/package.json
- Realization/frontend/czechidm-app/package.json
- Realization/frontend/czechidm-core/package.json
- Realization/frontend/czechidm-example/package.json
- Realization/frontend/czechidm-rpt/package.json
- Realization/frontend/czechidm-vs/package.json
https://redmine.czechidm.com/issues/3324
> 3324, release 13.0.2

- Realization/frontend/czechidm-core/src/content/dashboards/button/ChangePermissionDashboardButton.js
https://redmine.czechidm.com/issues/3267
> 3267 Role assignment on imported user in created state leads to server error

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/api/adapter/AccIdentityAccountPluggableRoleAssignmentDeduplicator.java
- Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/model/service/util/MultiSourcePagedResource.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/AbstractRoleAssignmentService.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmRequestIdentityRoleService.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmRoleRequestService.java
- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/adapter/DefaultRequestRoleConceptAdapter.java
https://redmine.czechidm.com/issues/3313
> [#3313] Check for non persistent roles in Account deduplicator

- Docker/compose/docker-compose-czechidm-H2.yml
- Docker/compose/docker-compose-czechidm.yml
- Docker/images/czechidm/Dockerfile
- RELEASE.md
- Realization/backend/acc/pom.xml
- Realization/backend/aggregator/pom.xml
- Realization/backend/app/pom.xml
- Realization/backend/core/core-api/pom.xml
- Realization/backend/core/core-impl/pom.xml
- Realization/backend/core/core-test-api/pom.xml
- Realization/backend/core/pom.xml
- Realization/backend/example/pom.xml
- Realization/backend/ic/pom.xml
- Realization/backend/parent/pom.xml
- Realization/backend/rpt/pom.xml
- Realization/backend/rpt/rpt-api/pom.xml
- Realization/backend/rpt/rpt-impl/pom.xml
- Realization/backend/tool/pom.xml
- Realization/backend/vs/pom.xml
- Realization/frontend/czechidm-acc/package.json
- Realization/frontend/czechidm-app/package.json
- Realization/frontend/czechidm-core/package.json
- Realization/frontend/czechidm-example/package.json
- Realization/frontend/czechidm-rpt/package.json
- Realization/frontend/czechidm-vs/package.json
https://redmine.czechidm.com/issues/3325
> 3235, release 13.0.3

- Realization/backend/acc/pom.xml
- Realization/backend/aggregator/pom.xml
- Realization/backend/app/pom.xml
- Realization/backend/core/core-api/pom.xml
- Realization/backend/core/core-impl/pom.xml
- Realization/backend/core/core-test-api/pom.xml
- Realization/backend/core/pom.xml
- Realization/backend/example/pom.xml
- Realization/backend/ic/pom.xml
- Realization/backend/parent/pom.xml
- Realization/backend/rpt/pom.xml
- Realization/backend/rpt/rpt-api/pom.xml
- Realization/backend/rpt/rpt-impl/pom.xml
- Realization/backend/tool/pom.xml
- Realization/backend/vs/pom.xml
- Realization/frontend/czechidm-acc/package.json
- Realization/frontend/czechidm-app/package.json
- Realization/frontend/czechidm-core/package.json
- Realization/frontend/czechidm-example/package.json
- Realization/frontend/czechidm-rpt/package.json
- Realization/frontend/czechidm-vs/package.json
https://redmine.czechidm.com/issues/3325
> 3325, setting versions to snapshot

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/event/processor/provisioning/PrepareConnectorObjectProcessor.java
https://redmine.czechidm.com/issues/3333
> 3333, fixed an issue with the compare report

- MIGRATION.md
https://redmine.czechidm.com/issues/3336
> [#3336] Fix migration query

- Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
https://redmine.czechidm.com/issues/3355
> [#3355] Fix sorting by role name in concept table

- Realization/frontend/czechidm-core/src/content/requestrole/RoleRequestTable.js
https://redmine.czechidm.com/issues/3360
> [#3360] Show dynamic entity info in role request table

- Realization/frontend/czechidm-core/src/content/task/DynamicTaskDetail.js
https://redmine.czechidm.com/issues/3366
> [#3366] Fix displaying applicant info component in role approval tasks

- Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/service/impl/DefaultIdmRoleRequestService.java
https://redmine.czechidm.com/issues/3363
> [#3363] Fix copy roles for standard identity roles

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/AbstractAccountManagementService.java
https://redmine.czechidm.com/issues/3397
> [#3397] Only allow entity acount creation by assigning IdmIdentityRole

- Realization/frontend/czechidm-core/src/content/task/identityRole/DynamicTaskRoleConceptDetail.js
https://redmine.czechidm.com/issues/3395
> [#3395] Fix update of role concept from dynamic task detail page

- Realization/frontend/czechidm-acc/src/content/account/AccountRolesContent.js
- Realization/frontend/czechidm-core/src/content/identity/IdentityRoleTable.js
- Realization/frontend/czechidm-core/src/content/identity/IdentityRoleTableFilter.js
- Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
- Realization/frontend/czechidm-core/src/content/requestrole/RoleRequestDetail.js
https://redmine.czechidm.com/issues/3394
> [#3394] Fix accountId filtering in request role table

- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/bulk/action/impl/AccountStopManagingBulkAction.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/event/processor/AccountDeleteProcessor.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/api/AccIdentityAccountService.java
- Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccIdentityAccountService.java
- Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/bulk/action/impl/AccountStopManagingBulkActionTest.java
- Realization/backend/core/core-impl/src/test/java/eu/bcvsolutions/idm/core/bulk/action/impl/rolerequest/RoleRequestDeleteBulkActionIntegrationTest.java
https://redmine.czechidm.com/issues/3338
> [#3338] Fix AccountStopManagingBulkAction for accounts with protection

- Realization/frontend/czechidm-acc/src/content/system/SchemaAttributeDetail.js
Simple frontend change, tested both on new params and existing, seems like a safe change.
> Changed default values of system attribute properties to match most common

- Realization/frontend/README.md
> Updated readme to better explain what to do when setting up a FE module.
